refactor: consolidate checkout actions and add support for manual deployments with image tags

diff --git a/.github/actions/argocd-deployment/checkout-repositories/action.yaml b/.github/actions/argocd-deployment/checkout-repositories/action.yaml
--- a/.github/actions/argocd-deployment/checkout-repositories/action.yaml
+++ b/.github/actions/argocd-deployment/checkout-repositories/action.yaml
@@ -1,16 +1,27 @@
 ---
 name: 'Checkout Repositories'
-description: 'Checkout repositories (Local & helm-chart-app-values) for ArgoCD deployment.'
+description: 'Checkout repositories and init context variables for ArgoCD deployment.'
 
 inputs:
   app_name:
-    description: 'Name of the app to deploy.'
+    description: 'App Name to Deploy.'
     required: true
+
+  branch_name:
+    description: 'Branch Name to Checkout (Required for manual deploy).'
+    required: false
+  env_to_deploy:
+    description: 'Target Environment to Deploy. (Required for manual deploy).'
+    required: false
+  image_tag: 
+    description: 'Image Tag to Deploy. If not provided, the image will be built from the workflow branch.'
+    required: false
+
   github_token_checkout:
     description: 'The GitHub token to checkout helm_chart_template repository.'
     required: true
   helm_chart_template_ref:
-    description: 'The helm-chart-template branch name.'
+    description: 'If provided, the helm-chart-template repository will be checked out to this branch.'
     required: false
 
 outputs:
@@ -36,75 +47,95 @@ outputs:
 runs:
   using: "composite"
   steps:
-    - uses: actions/checkout@v4
-
     - id: init-context-vars
+      name: Init Context Variables
       run: |
-        export COMMIT_TIME=$( git show -s --format=%ct )
-        if [[ '${{ github.event_name }}' == 'pull_request' ]]; then
-          export BRANCH_NAME_LOCAL=$( echo $GITHUB_HEAD_REF )
-        elif [[ '${{ github.event_name }}' == 'push' ]]; then
-          export BRANCH_NAME_LOCAL=$( cut -d '/' -f 3 <<< "$GITHUB_REF" )
-        else
-          exit 1
-        fi
-        echo "branch_name=$( echo $BRANCH_NAME_LOCAL )" >> $GITHUB_OUTPUT
+        if [[ "${{ github.event_name }}" == 'workflow_dispatch' ]]; then
+          if [[ -z "${{ inputs.branch_name }}" ]]; then
+            echo "# 🚨 Checkout failed" > $GITHUB_STEP_SUMMARY
+            echo "## Reason" >> $GITHUB_STEP_SUMMARY
+            echo "Branch name not provided in a \`workflow_dispatch\` event." >> $GITHUB_STEP_SUMMARY
+            exit 1
+          else
+            export BRANCH_NAME=${{ inputs.branch_name }}
+          fi
 
-        if [[ "$BRANCH_NAME_LOCAL" == "master" || "$BRANCH_NAME_LOCAL" == "main" ]] &&
-           [[ "$GITHUB_REF" == "refs/heads/master" || "$GITHUB_REF" == "refs/heads/main" ]]; then
-          echo "env_to_deploy=prod" >> $GITHUB_OUTPUT
+          if [[ -z "${{ inputs.env_to_deploy }}" ]]; then
+            echo "# 🚨 Checkout failed" > $GITHUB_STEP_SUMMARY
+            echo "## Reason" >> $GITHUB_STEP_SUMMARY
+            echo "Environment not provided in a \`workflow_dispatch\` event." >> $GITHUB_STEP_SUMMARY
+            exit 1
+          else
+            export ENV_TO_DEPLOY=${{ inputs.env_to_deploy }}
+          fi
+
         else
-          echo "env_to_deploy=$( cut -d '-' -f 1 <<< "$BRANCH_NAME_LOCAL" )" >> $GITHUB_OUTPUT
+          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
+            export BRANCH_NAME=${{ github.head_ref }}
+
+            echo "The \`env_to_deploy\` extraction from the \`branch_name\` in a PR event is no longer available."
+            echo "You must use the \`argocd-get-env-to-deploy-on\` action to obtain the \`env_to_deploy\` value."
+            export ENV_TO_DEPLOY=NOT_DEFINED
+
+          elif [[ "${{ github.event_name }}" == "push" ]]; then
+            export BRANCH_NAME=${{ github.ref_name }}
+
+            if [[ "${{ github.ref }}" == "refs/heads/master" || "${{ github.ref }}" == "refs/heads/main" ]]; then
+              export ENV_TO_DEPLOY=prod
+            else
+              export ENV_TO_DEPLOY=${{ github.ref_name }}
+            fi
+
+          else
+            echo "# 🚨 Checkout failed" > $GITHUB_STEP_SUMMARY
+            echo "## Reason" >> $GITHUB_STEP_SUMMARY
+            echo "Event \`${{ github.event_name }}\` not supported." >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
         fi
 
-        echo "current_time=$( date -d@$COMMIT_TIME -u +"%Y-%m-%dT%H%M")" >> $GITHUB_OUTPUT
-        echo "short_sha=$( git rev-parse --short=7 "$GITHUB_SHA" )" >> $GITHUB_OUTPUT
+        if [[ -z "${{ inputs.image_tag }}" ]]; then
+          export COMMIT_TIME=$( git show -s --format=%ct )
+          export CURRENT_TIME=$( date -d@$COMMIT_TIME -u +"%Y-%m-%dT%H%M")
+          export SHORT_SHA=$( git rev-parse --short=7 "$GITHUB_SHA" )
+          export IMAGE_TAG=$BRANCH_NAME-$CURRENT_TIME-$SHORT_SHA
+        else
+          export CURRENT_TIME=NO_TIME
+          export SHORT_SHA=NO_SHA
+          export IMAGE_TAG=${{ inputs.image_tag }}
+        fi
+
+        echo "branch_name=$( echo $BRANCH_NAME )" >> $GITHUB_OUTPUT
+        echo "env_to_deploy=$( echo $ENV_TO_DEPLOY )" >> $GITHUB_OUTPUT
+        echo "current_time=$( echo $CURRENT_TIME )" >> $GITHUB_OUTPUT
+        echo "short_sha=$( echo $SHORT_SHA )" >> $GITHUB_OUTPUT
+        echo "image_tag=$( echo $IMAGE_TAG )" >> $GITHUB_OUTPUT
       shell: bash
 
     - uses: actions/checkout@v4
-      if: (inputs.github_token_checkout != '' && github.event.pull_request.user.login != 'dependabot[bot]') &&
-          (github.event_name == 'push') && 
+      with:
+        ref: ${{ inputs.branch_name }}
+
+    - uses: actions/checkout@v4
+      if: github.event_name == 'push' && 
           (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main') &&
-          (steps.init-context-vars.outputs.branch_name == 'master' || steps.init-context-vars.outputs.branch_name == 'main') &&
-          (steps.init-context-vars.outputs.env_to_deploy == 'prod')
+          steps.init-context-vars.outputs.env_to_deploy == 'prod' &&
+          (steps.init-context-vars.outputs.branch_name == 'master' || steps.init-context-vars.outputs.branch_name == 'main')
       with:
         repository: fcm-digital/helm-chart-${{ inputs.app_name }}-values
         token: ${{ inputs.github_token_checkout }}
-        ref: ${{ env.BRANCH_NAME }}
+        ref: ${{ steps.init-context-vars.outputs.branch_name }}
         path: helm-chart-${{ inputs.app_name }}-values-prod
 
     - uses: actions/checkout@v4
-      if: (inputs.github_token_checkout != '' && github.event.pull_request.user.login != 'dependabot[bot]')
       with:
         repository: fcm-digital/helm-chart-${{ inputs.app_name }}-values
         token: ${{ inputs.github_token_checkout }}
         ref: staging
         path: helm-chart-${{ inputs.app_name }}-values-staging
 
-    - id: check-environment
-      run: |
-        if [ ! -d helm-chart-${{ inputs.app_name }}-values-staging ] && [ ! -d helm-chart-${{ inputs.app_name }}-values-prod ]; then
-            echo "deploy_on_existing_env=false" >> $GITHUB_OUTPUT
-            echo "No deployment will be needed."
-        elif [ "${{ steps.init-context-vars.outputs.env_to_deploy }}" = "prod" ]; then
-          echo "All Repositories were properly cloned!"
-          echo "deploy_on_existing_env=true" >> $GITHUB_OUTPUT
-        else
-          cd helm-chart-${{ inputs.app_name }}-values-staging/staging
-          if [ ! -d ${{ steps.init-context-vars.outputs.env_to_deploy }} ]; then
-            echo "Environment does not exist. No deployment will be needed."
-            echo "deploy_on_existing_env=false" >> $GITHUB_OUTPUT
-          else
-            echo "All Repositories were properly cloned!"
-            echo "deploy_on_existing_env=true" >> $GITHUB_OUTPUT
-          fi
-        fi
-      shell: bash
-
     - uses: actions/checkout@v4
-      if: inputs.github_token_checkout != '' &&
-          github.event.pull_request.user.login != 'dependabot[bot]' && 
-          inputs.helm_chart_template_ref != ''
+      if: inputs.helm_chart_template_ref != ''
       with:
         repository: fcm-digital/helm-chart-template
         token: ${{ inputs.github_token_checkout }}
