split action into 3 different github actions

diff --git a/.github/actions/github/get-workflow-id/action.yaml b/.github/actions/github/get-workflow-id/action.yaml
--- a/.github/actions/github/get-workflow-id/action.yaml
+++ b/.github/actions/github/get-workflow-id/action.yaml
@@ -3,19 +3,13 @@ name: 'Get Workflow ID'
 description: 'Get the ID of a GitHub workflow based on the workflow file name and repository.'
 
 inputs:
-  github_app_id:
-    description: 'The GitHub App ID. (Required if github_token is not provided)'
-    required: false
-  github_app_private_key:
-    description: 'The GitHub App private key. (Required if github_token is not provided)'
-    required: false
   github_token:
-    description: 'The GitHub Token. (Required if github_app_id and github_app_private_key are not provided)'
+    description: 'The GitHub Token.'
     required: false
   github_organization_name:
     description: 'The GitHub organization name.'
     required: true
-  repository_name:
+  github_repository_name:
     description: 'The repository name.'
     required: true
   workflow_file_name:
@@ -30,43 +24,24 @@ outputs:
 runs:
   using: "composite"
   steps:
-    - name: Generate a GH Token
-      if: inputs.github_token == '' && inputs.github_app_id != '' && inputs.github_app_private_key != ''
-      id: generate-gh-token
-      uses: actions/create-github-app-token@v2
-      with:
-        app-id: ${{ inputs.github_app_id }}
-        private-key: ${{ inputs.github_app_private_key }}
-        owner: ${{ inputs.github_organization_name }}
-        repositories: ${{ inputs.repository_name }}
-
     - id: get-workflow-id
       name: Get Workflow ID
       env:
-        GH_TOKEN: ${{ steps.generate-gh-token.outputs.token || inputs.github_token }}
-        GH_DEBUG: api
+        GH_TOKEN: ${{ inputs.github_token }}
+        GH_OUTPUT_FILE_NAME: gh-output.json
       run: |
-        gh auth status
+        gh workflow list --repo ${{ inputs.github_organization_name }}/${{ inputs.github_repository_name }} --json id,path) > $GH_OUTPUT_FILE_NAME
 
-        # gh api \
-        #   -H "Accept: application/vnd.github+json" \
-        #   -H "X-GitHub-Api-Version: 2022-11-28" \
-        #   /repos/${{ inputs.github_organization_name }}/${{ inputs.repository_name }}/actions/workflows
+        if [[ $? -ne 0 ]] || [ ! -f "$GH_OUTPUT_FILE_NAME" ] && [ ! -s "$GH_OUTPUT_FILE_NAME" ]; then
+          echo "Failed to list workflows"
+          exit 1
+        fi
 
-        gh workflow list --repo ${{ inputs.github_organization_name }}/${{ inputs.repository_name }} --json id,name
+        WORKFLOW_ID=$(cat $GH_OUTPUT_FILE_NAME | jq --arg workflowFileName "${{ inputs.workflow_file_name }}" '.[] | select(.path | contains($workflowFileName))' | jq '.id')
 
-        # if [[ $? -ne 0 ]] || [[ -z $WORKFLOWS_DATA ]]; then
-        #   echo "Failed to list workflows"
-        #   exit 1
-        # fi
-
-        # echo "WORKFLOWS_DATA: $WORKFLOWS_DATA"
-
-        # WORKFLOW_ID=$(echo $WORKFLOWS_DATA | jq --arg workflowFileName "${{ inputs.workflow_file_name }}" '.workflows[] | select(.path | contains($workflowFileName))' | jq '.id')
-
-        # if [[ $? -ne 0 ]] || [[ -z $WORKFLOW_ID ]]; then
-        #   echo "Failed to get workflow ID"
-        #   exit 1
-        # fi
-        # echo "workflow_id=$WORKFLOW_ID" >> $GITHUB_OUTPUT
+        if [[ $? -ne 0 ]] || [[ -z $WORKFLOW_ID ]]; then
+          echo "Failed to get workflow ID"
+          exit 1
+        fi
+        echo "workflow_id=$WORKFLOW_ID" >> $GITHUB_OUTPUT
       shell: bash
